#logging:
#  level:
#    root: DEBUG

#logging:
#  level:
#    org:
#      springframework:
#        security: DEBUG

#  cloud:
#    consul:
#      discovery:
#        health-check-interval: 1m

logging:
  level:
    org:
      springframework:
        data:
          mongodb: DEBUG
spring:
  data:
    mongodb:
      database: applicants
      port: 27017
      host: 0.0.0.0
